### ISSUE TITLE
Great project

### ISSUE THREAD

**Issue by tinohager** [kinnajowa/FreeZVT#1]
Maybe you would like to link to our projects in the documentation.

- https://github.com/Portalum/Portalum.Zvt
- https://github.com/Portalum/Portalum.Zvt.EasyPay

In addition, it would be useful to add the tags to your project so that other people can find it more easily.

![image](https://user-images.githubusercontent.com/8215186/186664331-1bca4e91-7e70-477c-bba8-e41d9a28b802.png)

Also a listing of the available parameters would look great in the readme. Is there a plan to provide a ready to use Docker image here?

**Comment by tinohager** [comment]
Can you add `Topics` that would be really great, for example `zvt`?

**Comment by kinnajowa** [comment]
There is no need for a docker image since the goal of this project is to provide an open-source "in-place" alternative for the commercal tool EasyZVT. This tools uses the windows registry to communicate with other processes, so it's not designed to run in a docker container.

**Comment by tinohager** [comment]
Okay then it would be very great if there is a ready release to download.
Simular as here: https://github.com/Portalum/Portalum.Zvt/releases
